### PR TITLE
Velocity support

### LINKED ISSUE #93: Exception encountered when loading plugin: NuVotifier
Just updated nuvotifier. Last update was May 27th from:
https://repo.parallelblock.com/repository/public-raw/nuvotifier/nuvotifier.jar
I'm now getting this:

Reverting fixes my issue.
Did something change?

```
05:28:09 [INFO] [NuVotifier] Loaded token for website: default
05:28:09 [INFO] [NuVotifier] Votifier enabled on socket /0:0:0:0:0:0:0:0:8192.
05:28:09 [WARNING] Exception encountered when loading plugin: NuVotifier
java.lang.NoSuchMethodError: com.google.gson.JsonObject.keySet()Ljava/util/Set;
	at com.vexsoftware.votifier.bungee.forwarding.cache.FileVoteCache.load(FileVoteCache.java:70)
	at com.vexsoftware.votifier.bungee.forwarding.cache.FileVoteCache.<init>(FileVoteCache.java:32)
	at com.vexsoftware.votifier.bungee.NuVotifier.loadAndBind(NuVotifier.java:258)
	at com.vexsoftware.votifier.bungee.NuVotifier.onEnable(NuVotifier.java:321)
	at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:227)
	at net.md_5.bungee.BungeeCord.start(BungeeCord.java:281)
	at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:56)
	at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
```

### PR DESCRIPTION
**Pull request by astei**
This PR adds support for the [Velocity](https://www.velocitypowered.com) proxy.

Underneath all of this is basically a refactor of NuVotifier to share more platform-independent code and to abstract out the vote forwarding stuff so that it can be used on other platforms.

The port is almost fully featured (I need reload functionality), but the proxy-side components work exactly how the BungeeCord port does it.

This also fixes #93 and issues with Sponge forwarding not working by default.

### CODE REVIEW

**Comment by andrewkm** [comment]
+1

File: bukkit/src/main/java/com/vexsoftware/votifier/NuVotifierBukkit.java [hunk 1]
```diff
@@ -288,15 +253,8 @@ protected void initChannel(NioSocketChannel channel) {
...
-            try {
-                if (serverChannel != null)
-                    serverChannel.close().sync();
-                serverGroup.shutdownGracefully().sync();
-            } catch (Exception e) {
-                getLogger().log(Level.SEVERE, "Unable to shut down listening port gracefully.", e);
-            }
-            serverGroup = null;
+        if (bootstrap != null) {
+            bootstrap.shutdown();
```
Comment (Ichbinjoe) [inline bukkit/src/main/java/com/vexsoftware/votifier/NuVotifierBukkit.java]: It is an error to close the bootstrap more than once - should be set to null.

File: bukkit/src/main/java/com/vexsoftware/votifier/NuVotifierBukkit.java [hunk 2]
```diff
@@ -375,6 +333,16 @@ public String getVersion() {
...
     }
 
+    @Override
+    public Logger getPluginLogger() {
+        return FACTORY.getLogger(getLogger().getName());
+    }
+
+    @Override
+    public VotifierScheduler getScheduler() {
+        return new BukkitScheduler(this);
```
Comment (Ichbinjoe) [inline bukkit/src/main/java/com/vexsoftware/votifier/NuVotifierBukkit.java]: Should be a singleton

File: common/src/main/java/com/vexsoftware/votifier/platform/ProxyVotifierPlugin.java [hunk 3]
```diff
@@ -0,0 +1,10 @@
+package com.vexsoftware.votifier.platform;
+
+import java.util.List;
+import java.util.Optional;
+
+public interface ProxyVotifierPlugin extends VotifierPlugin {
+    List<BackendServer> getAllBackendServers();
```
Comment (Ichbinjoe) [inline common/src/main/java/com/vexsoftware/votifier/platform/ProxyVotifierPlugin.java]: Can (and should) be a Collection<>

File: bungeecord/src/main/java/com/vexsoftware/votifier/bungee/NuVotifier.java [hunk 4]
```diff
@@ -424,7 +376,32 @@ public String getVersion() {
...
+    public VotifierScheduler getScheduler() {
+        return new BungeeScheduler(this);
+    }
+
     public boolean isDebug() {
         return debug;
     }
+
+    @Override
+    public List<BackendServer> getAllBackendServers() {
```
Comment (Ichbinjoe) [inline bungeecord/src/main/java/com/vexsoftware/votifier/bungee/NuVotifier.java]: List -> Collection (another comment highlights this change in the interface)

File: bungeecord/src/main/java/com/vexsoftware/votifier/bungee/OnlineForwardPluginMessagingForwardingSource.java [hunk 5]
```diff
@@ -27,32 +28,30 @@ public OnlineForwardPluginMessagingForwardingSource(String channel, NuVotifier n
...
     @EventHandler
     public void onServerConnected(final ServerConnectedEvent e) { //Attempt to resend any votes that were previously cached.
-        handleServerConnected(e);
-    }
-
-    @EventHandler
-    public void onPlayerSwitch(ServerConnectedEvent e) {
-        handlePlayerSwitch(e);
+        BackendServer server = new BungeeBackendServer(e.getServer().getInfo());
+        handlePlayerSwitch(new BungeeBackendServer(e.getServer().getInfo()), e.getPlayer().getName());
```
Comment (Ichbinjoe) [inline bungeecord/src/main/java/com/vexsoftware/votifier/bungee/OnlineForwardPluginMessagingForwardingSource.java]: should use server, not instantiate a new one

File: bungeecord/src/main/java/com/vexsoftware/votifier/bungee/NuVotifier.java [hunk 6]
```diff
@@ -424,7 +376,32 @@ public String getVersion() {
...
+    @Override
+    public Logger getPluginLogger() {
+        // Well, Bungee doesn't make it any easier on us to do this. We get to do something terrible and there's nothing
+        // we can do about it!
+        return DirtyTricks.getLogger(getLogger());
+    }
+
+    @Override
+    public VotifierScheduler getScheduler() {
+        return new BungeeScheduler(this);
```
Comment (Ichbinjoe) [inline bungeecord/src/main/java/com/vexsoftware/votifier/bungee/NuVotifier.java]: should be a singleton - called multiple times

File: bungeecord/src/main/java/com/vexsoftware/votifier/bungee/NuVotifier.java [hunk 7]
```diff
@@ -424,7 +376,32 @@ public String getVersion() {
         return getDescription().getVersion();
     }
 
+    @Override
+    public Logger getPluginLogger() {
+        // Well, Bungee doesn't make it any easier on us to do this. We get to do something terrible and there's nothing
+        // we can do about it!
+        return DirtyTricks.getLogger(getLogger());
```
Comment (Ichbinjoe) [inline bungeecord/src/main/java/com/vexsoftware/votifier/bungee/NuVotifier.java]: should be a singleton - called multiple times

File: common/src/main/java/com/vexsoftware/votifier/support/forwarding/cache/FileVoteCache.java [hunk 8]
```diff
@@ -67,11 +75,11 @@ private void load() throws IOException {
         JsonObject players = object.getAsJsonObject("players");
         JsonObject servers = object.getAsJsonObject("servers");
 
-        for (String player : players.keySet()) {
+        for (String player : keySet(players)) {
```
Comment (Ichbinjoe) [inline common/src/main/java/com/vexsoftware/votifier/support/forwarding/cache/FileVoteCache.java]: Not saying its wrong, but why was this changed?

File: common/src/main/java/com/vexsoftware/votifier/util/standalone/StandaloneVotifierPlugin.java [hunk 9]
```diff
@@ -77,6 +59,16 @@ public String getVersion() {
         return "2.3.5";
```
Comment (Ichbinjoe) [inline common/src/main/java/com/vexsoftware/votifier/util/standalone/StandaloneVotifierPlugin.java]: WOW this hasn't been updated in awhile.

Do we need this?

File: common/src/main/java/com/vexsoftware/votifier/util/standalone/StandaloneVotifierPlugin.java [hunk 10]
```diff
@@ -1,65 +1,47 @@
...
-                    }
-                })
-                .bind(bind)
-                .syncUninterruptibly();
-
-        if (!future.isSuccess()) {
-            return future.cause();
-        } else {
-            return null;
+    public void start(Consumer<Throwable> error) {
```
Comment (Ichbinjoe) [inline common/src/main/java/com/vexsoftware/votifier/util/standalone/StandaloneVotifierPlugin.java]: Now _technically_ we should maintain backwards compat. and have a 0 argument start

Comment (Ichbinjoe) [reply common/src/main/java/com/vexsoftware/votifier/util/standalone/StandaloneVotifierPlugin.java]: Should also handle the case where error is null

File: common/src/main/java/com/vexsoftware/votifier/util/standalone/StandaloneVotifierPlugin.java (hunk 9 above)
Comment (Ichbinjoe) [reply common/src/main/java/com/vexsoftware/votifier/util/standalone/StandaloneVotifierPlugin.java]: So we really do need this, but maybe it should be in the interest of security to simply respond "2"

File: common/src/test/java/com/vexsoftware/votifier/net/protocol/TestVotifierPlugin.java [hunk 11]
```diff
@@ -75,6 +80,16 @@ public String getVersion() {
         return "2.3";
```
Comment (Ichbinjoe) [inline common/src/test/java/com/vexsoftware/votifier/net/protocol/TestVotifierPlugin.java]: See comment above about protocol versions

File: sponge/src/main/java/com/vexsoftware/votifier/sponge/VotifierPlugin.java [hunk 12]
```diff
@@ -217,6 +171,16 @@ public String getVersion() {
...
     }
 
+    @Override
+    public Logger getPluginLogger() {
+        return logger;
+    }
+
+    @Override
+    public VotifierScheduler getScheduler() {
+        return new SpongeScheduler(this);
```
Comment (Ichbinjoe) [inline sponge/src/main/java/com/vexsoftware/votifier/sponge/VotifierPlugin.java]: should be a singleton

File: universal/build.gradle [hunk 13]
```diff
@@ -13,11 +13,13 @@ dependencies {
     compile project(":nuvotifier-bukkit")
     compile project(":nuvotifier-bungeecord")
     compile project(":nuvotifier-sponge")
+    compile project(":nuvotifier-velocity")
 }
 
 shadowJar {
     baseName = 'nuvotifier'
     classifier = null
+    //relocate "org.slf4j", "com.vexsoftware.votifier.slf4j"
```
Comment (Ichbinjoe) [inline universal/build.gradle]: Do we need this?

If not, get rid of it.

File: velocity/src/main/java/com/vexsoftware/votifier/velocity/OnlineForwardPluginMessagingForwardingSource.java [hunk 14]
```diff
@@ -0,0 +1,53 @@
...
+        this.plugin = plugin;
+        plugin.getServer().getEventManager().register(plugin, this);
+        plugin.getServer().getChannelRegistrar().register((source, side, identifier, data) -> MessageHandler.ForwardStatus.HANDLED, VelocityUtil.getId(channel));
+    }
+
+    @Override
+    public void forward(Vote v) {
+        Optional<Player> p = plugin.getServer().getPlayer(v.getUsername());
+        Optional<ServerConnection> sc = p.flatMap(Player::getCurrentServer);
+        if (p.isPresent() && sc.isPresent()) {
```
Comment (Ichbinjoe) [inline velocity/src/main/java/com/vexsoftware/votifier/velocity/OnlineForwardPluginMessagingForwardingSource.java]: If sc is present, then p will always be present. Simplify.

File: velocity/src/main/java/com/vexsoftware/votifier/velocity/VelocityBackendServer.java [hunk 15]
```diff
@@ -0,0 +1,42 @@
...
+        return info.getName();
+    }
+
+    @Override
+    public boolean sendPluginMessage(String channel, byte[] data) {
+        Optional<ServerConnection> connection = server.getAllPlayers().stream()
+                .map(p -> p.getCurrentServer().filter(s -> s.getServerInfo().equals(info)))
+                .filter(Optional::isPresent)
+                .findAny()
+                .flatMap(o -> o);
```
Comment (Ichbinjoe) [inline velocity/src/main/java/com/vexsoftware/votifier/velocity/VelocityBackendServer.java]: am i missing something?

File: common/src/main/java/com/vexsoftware/votifier/support/forwarding/cache/FileVoteCache.java (hunk 8 above)
Comment (astei) [reply common/src/main/java/com/vexsoftware/votifier/support/forwarding/cache/FileVoteCache.java]: See #93 for more information, but essentially this didn't work on BungeeCord because BungeeCord has an older GSON version (2.8.0) that lacks `keySet()` on `JsonObject`.

File: common/src/main/java/com/vexsoftware/votifier/util/standalone/StandaloneVotifierPlugin.java (hunk 9 above)
Comment (astei) [reply common/src/main/java/com/vexsoftware/votifier/util/standalone/StandaloneVotifierPlugin.java]: We don't really need this, I can change it to 2.

File: velocity/src/main/java/com/vexsoftware/votifier/velocity/VelocityBackendServer.java (hunk 15 above)
Comment (astei) [reply velocity/src/main/java/com/vexsoftware/votifier/velocity/VelocityBackendServer.java]: We get an `Optional<Optional<ServerConnection>>` here, this is simply the identity function to unpack it.

File: common/src/test/java/com/vexsoftware/votifier/net/protocol/TestVotifierPlugin.java (hunk 11 above)
Comment (astei) [reply common/src/test/java/com/vexsoftware/votifier/net/protocol/TestVotifierPlugin.java]: I'll just change this to "2".
